In [ ]:
import numpy as np

# Datos de ejemplo (serie temporal simple)
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
data

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Función para crear secuencias
def create_sequences(data, seq_length=3):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i+seq_length])  # Secuencia de entrada (X)
        y.append(data[i+seq_length])    # Valor a predecir (y)
    return np.array(X), np.array(y)

In [ ]:
# Crear secuencias con longitud 3
seq_length = 3
X, y = create_sequences(data, seq_length)
# Mostrar los resultados
print("X (Secuencias de entrada):")
print(X)
print("\ny (Valores esperados):")
print(y)

X (Secuencias de entrada):
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]]

y (Valores esperados):
[40 50 60 70 80]


In [ ]:
# Redimensionar X para que tenga la forma adecuada para LSTM: (samples, timesteps, features)
X = X.reshape((X.shape[0], X.shape[1], 1))  # Agregar dimensión de características
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]]])

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
# Crear el modelo LSTM
model = Sequential([
    LSTM(50, activation='relu', input_shape=(seq_length, 1)),  # Capa LSTM con 50 neuronas
    Dense(1)  # Capa de salida con 1 neurona para predecir el siguiente valor
])
# Compilar el modelo
model.compile(optimizer='adam', loss='mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
# Entrenar el modelo
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 3476.6060
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - loss: 3441.1047
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 3405.1235
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 3368.7043
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 3331.8999
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 3294.7749
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 3257.3999
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 3219.8477
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 3182.1929
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 3144.5061
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 3106.8513
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 3069.2847
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 3031.8501
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2994.5815
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s

In [ ]:
# Hacer una predicción
last_sequence = np.array([60, 70, 80]).reshape((1, seq_length, 1))  # Últimos 3 valores como entrada
predicted_value = model.predict(last_sequence)
next_value = predicted_value[0][0]
print(f"\n🔮 Predicción del siguiente valor después de 80: {next_value:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

🔮 Predicción del siguiente valor después de 80: 91.02
