# PRIMEROS PASOS CON PYTORCH

## IMPORTAMOS PYTORCH

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

## TENSORES

In [2]:
array = [1,2,3]
type(array)

list

In [4]:
escalar = torch.randn(1)
type(escalar)

torch.Tensor

In [5]:
vector = torch.zeros(1,10)
vector

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
type(vector)

torch.Tensor

# CREAMOS NUESTRA PRIMERA RED NEURONAL CON PYTORCH

## 1 - IMPORTAMOS LIBRERIAS

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

## 2 - CREAMOS UNA CLASE PARA NUESTRO MODELO DE RED NEURONAL

In [8]:
class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN,self).__init__()
    self.fc = nn.Linear(2,1) #creamos una capa con 2 neuronas de entrara y 1 de salida

  def forward(self,x):
    return self.fc(x)

## 3 - CREAMOS UN OBJETO DE CLASE DE NUESTRO MODELO Y DEFINIMOS FUNCIÓN DE PERDIA Y OPTIMIZADOR

In [10]:
model = SimpleNN()
criterion = nn.MSELoss()# error cuadratico medio
optimizer = optim.SGD(model.parameters(),lr=0.01) # Descenso de Gradiente Estocástico (SGD, Stochastic Gradient Descent),

## 4 - CREAMOS UN DATASET DE PRUEBA PARA ENTRENAR NUESTRO MODELO

In [11]:
inputs = torch.tensor([[1.0,2.0],[2.0,3.0]],dtype=torch.float32)
inputs

tensor([[1., 2.],
        [2., 3.]])

In [12]:
labels = torch.tensor([[1.0],[2.0]],dtype=torch.float32)
labels

tensor([[1.],
        [2.]])

## 5 - ENTRENAMOS EL MODELO

In [14]:
epochs = 10
for epoch in range(epochs):
  outputs = model(inputs) #hacemos un predicción con el modelo
  loss = criterion(outputs,labels) # calculamos la perdida

  #backprogration y optimización
  optimizer.zero_grad() # reiniciar los gradientes para evitar acumulaciones incorrectas.
  loss.backward() # Calcular los gradientes
  optimizer.step() # Actualizar los pesos del modelo
  print(f'epoca {epoch + 1}, loss: {loss.item():.4f}')

  if(epoch + 1) % 10 == 0:
    print(f'resultado final : epoca {epoch + 1}, loss : {loss.item():.4f}')

epoca 1, loss: 0.0878
epoca 2, loss: 0.0592
epoca 3, loss: 0.0408
epoca 4, loss: 0.0290
epoca 5, loss: 0.0214
epoca 6, loss: 0.0165
epoca 7, loss: 0.0133
epoca 8, loss: 0.0113
epoca 9, loss: 0.0100
epoca 10, loss: 0.0091
resultado final : epoca 10, loss : 0.0091


## 6 PREDICCIONES DEL MODELO

In [16]:
import numpy as np
print(f'valores predichos : {np.round(model(inputs).detach().numpy())}')
print(f'valores reales :{labels}')

valores predichos : [[1.]
 [2.]]
valores reales :tensor([[1.],
        [2.]])
